@ECHO OFF
ECHO Creating output dir...
MKDIR bin
ECHO Compiling code...
JAVAC -d bin -cp ".;./lib/gson-2.6.2.jar;./lib/opencsv-3.7.jar;./src;./resources" src/main/PhoneBook.java
ECHO Copying resources...
COPY src\main\view\*.fxml bin\main\view
ECHO Running PhoneBook v0.1 app...
JAVA -cp ".;./lib/gson-2.6.2.jar;./lib/opencsv-3.7.jar;./bin;./resources" main.PhoneBook
ECHO Delete temp files and quit
RMDIR /s/q bin